MACROS:
  RM_IHPSG13_2P_1024x16_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_2P_1024x16_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_2P_1024x16_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_1024x16_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_core_behavioral_bm_bist_ideal.v
    lib:
      "nom_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
      "nom_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
      "nom_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      # Make sure to specify the SRAMs in pdn_cfg.tcl
      chip_core.fb.sram0:
        location: [590, 590]
        orientation: N

# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- "chip_core.fb.sram0 VDD VSS VDDARRAY! VSS!"
- "chip_core.fb.sram0 VDD VSS VDD! VSS!"
#- "chip_core.sram_1 VDD VSS VDDARRAY! VSS!"
#- "chip_core.sram_1 VDD VSS VDD! VSS!"
#- "chip_core.sram_2 VDD VSS VDDARRAY! VSS!"
#- "chip_core.sram_2 VDD VSS VDD! VSS!"

# Custom PDN config to connect to SRAMs
PDN_CFG: dir::pdn_cfg.tcl
